retention:
  count_based:
    enabled: false
    max_entries: 10000
  export:
    enabled: true
    format: csv_zip
    include_timestamp: true
    output_directory: exports
  schedule:
    interval_hours: 24
    last_execution: '2025-06-05T19:38:35.129883+00:00'
    on_startup: true
  time_based:
    duration: 7d
    enabled: true
